services:
  - type: web
    name: crmhay
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --preload --max-requests 500 --max-requests-jitter 50
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        sync: false
      - key: CRM_SECRET_KEY
        sync: false
      - key: CRM_ADMIN_USERNAME
        sync: false
      - key: CRM_ADMIN_PASSWORD
        sync: false
      - key: CRM_HOTLINE_NUMBERS
        sync: false
